---
cog_bundle_version: 3

name: pagerduty
version: 0.0.2
description: Interact with pagerduty
permissions:
  - pagerduty:read
  - pagerduty:write
  - pagerduty:alert
commands:
  alert:
    executable: /home/bundle/cog-command
    description: Trigger alerts
    documentation: |
      pagerduty:alert [-s|--service <service name>] <msg> - Trigger an alert on the specified service
      pagerduty:alert <msg> - Trigger an alert on the default service

      Returns a confirmation message on success
    rules:
      - must have pagerduty:alert
    options:
      service:
        type: string
        required: false
        short_flag: s
  oncall:
    executable: /home/bundle/cog-command
    description: Find out who is on-call for all services, or for a specific service
    documentation: |
      pagerduty:oncall - Retrieve a list of services and the name and email of the primary oncall
      pagerduty:oncall <service> - Retrieve the oncall for the sepcified service
    rules: ["allow"]
  ack:
    executable: /home/bundle/cog-command
    description: Acknowledge incidents
    documentation: |
      pagerduty:ack <incident id> - Acknowledge the incident
      pagerduty:ack [-a | --as <pagerduty user email>] <incident id> Acknowledge the incident as the account specified by the email

      Returns confirmation of acknowledgement
    rules:
      - must have pagerduty:write
    options:
      as:
        type: string
        required: false
        short_flag: a
  resolve:
    executable: /home/bundle/cog-command
    description: Resolve incidents
    documentation: |
      pagerduty:resolve <incident id> - Resolve the incident
      pagerduty:resolve [-a | --as <pagerduty user email>] <incident id> Resolve the incident as the account specified by the email

      Returns confirmation of resolution
    rules:
      - must have pagerduty:write
    options:
      as:
        type: string
        required: false
        short_flag: a
  incidents:
    executable: /home/bundle/cog-command
    description: List incidents
    documentation: |
      pagerduty:incidents [-a | --acked] [-t | --triggered] [-r | --resolved] [-l | --limit]

      Retrieves incidents matching the specified option. By default, only returns triggered incidents.
    rules:
      - must have pagerduty:read
    options:
      triggered:
        type: bool
        required: false
        short_flag: t
      acked:
        type: bool
        required: false
        short_flag: a
      resolved:
        type: bool
        required: false
        short_flag: r
      limit:
        type: int
        required: false
        short_flag: l
templates:
  oncall:
    slack: "{{ name }} - {{ oncall.name }}({{ oncall.email }})"
    hipchat: "{{ name }} - {{ oncall.name }}({{ oncall.email }})"
  incidents:
    slack: "Service: {{ service.name }} {{ url }}\nStatus: {{ status }}\n{{ summary.subject }} {{ summary.description }}\n"
    hipchat: "Service: {{ service.name }} {{ url }}\nStatus: {{ status }}\n{{ summary.subject }} {{ summary.description }}\n"
  noresults:
    slack: "Sorry, no results were returned."
    hipchat: "Sorry, no results were returned."
